spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds-master, ds-slave-0, ds-slave-1
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.99.101:3306/orders_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      ds-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.99.101:3306/orders_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      ds-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.99.101:3307/orders_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      slave-data-source-names: ds-slave-0, ds-slave-1
      master-data-source-name: ds-master
      name: ms

# mybatis 配置内容
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: none
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath*:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: fun.happyhacker.springbootdemo.mybatis.dataobject

logging:
  level:
    root: debug